[pytest]
minversion = 9.0
addopts = -v -ra
    --alluredir allure-results
    --clean-alluredir
testpaths = tests

log_cli = true
log_cli_level = INFO

markers =
    smoke: быстрые критические тесты для проверки базовой работоспособности
    regression: полные регрессионные тесты
    negative: негативые проверки
    positive: позитивные проверки
    ui: проверки интерфейса